const Faked=[
    { courseName:'ielts',duration:'three month',price:3000},
    { courseName:'gre',duration:'three month',price:5000},
    { courseName:'kids',duration:'four month',price:5000},
    { courseName:'math',duration:'five month',price:3000},
    { courseName:'math',duration:'six month',price:9000},
    { courseName:'bangla',duration:'seven month',price:7000},
    { courseName:'history',duration:'eight month',price:3000},
    { courseName:'englis',duration:'nine month',price:11000},
    { courseName:'quran',duration:'ten month',price:3000},
    { courseName:'speaking',duration:'one month',price:43000},
    { courseName:'national english',duration:'two month',price:3000},
    { courseName:'international english',duration:'five month',price:3000},
    { courseName:'bangla',duration:'six month',price:7000},
    { courseName:'physics',duration:'eight month',price:3000},
    { courseName:'chemistry',duration:'three month',price:12000},
]